### ISSUE TITLE
Documenting your experiences to develop in the Solid/LD ecosystem

### ISSUE THREAD

**Issue by th0rgall** [osoc22/project-idlab#49]

**Comment by Matei9721** [comment]
I will reformat this comment later, but I am sharing stuff now so I don't forget.

- There is a steep learning curve for linked data which is mainly because all the educational websites are pretty old, and there are no new examples.
- There are not that many linked and open data sets out there that one can use to build an application. Most of them are related to education which doesn't work that well with a real-life use case app.
- It was very hard to find/understand how to make specifications for the linked data. Not knowing what schemas and ontologies to use was really annoying.
- A good amount of the resources we found were archived or no longer available. Moreover, there were no example applications that combined all the technologies we used so we had to piece all the small examples together to get a working demo.
- I believe we still do not take full advantage of the power of linked data, but because of the short time we had to get a grasp of the situation, and also build, I don't think much more could have been done.

**Comment by th0rgall** [comment]
I tried to list many of the higher-level issues you've experienced with the LD ecosystem, please use from this as much as you want https://thorgalle.notion.site/Feedback-for-Solid-LD-3faa05dcf2ac4e5491d149b9e8e1ef02

Consider also how you would improve the situation :)

**Comment by Denperidge** [comment]
OKAY so there's a lot of thoughts here

**Open data**
The vision of open data is something I wholeheartedly support. The TED talk that was shown was very inspirational and did genuinely remotivate me

**Linked data/RDF**
This is a _tough_ one. Linked Data is a really cool and good idea, but it is held back by the incredibly steep learning curve, numerous dead links and resources, non-human-readable/writeable or kind of bloated file formats (you can write a JSON file by hand, but RDF? oh no). The biggest hope I see for Linked Data is the support of large entities. DBpedia/Wikipedia and Europe for example. But this reliance on longevity and size also kind of defeats the purpose a bit I feel?

**Solid**
Solid I like a lot more. The Inrupt clients - as tough as they were to get started with - ended up being incredibly nice to work with. The idea of being able to choose where to host, including but not limited to yourself, is a great idea, and many of the solid specs' ideas are amazing. It is however not consumer ready; considering the current lack of secure & consistent of public hosts and well maintained apps to hook into those hosts means this service is barely ready to be used by tech people, let alone your regular consumer (although both those can be fixed over time). My main long-term concern is the same with all decentralised technologies; if Solid has any longevity, I hope it'll be less of an ecological disaster than some other decentralised technologies.


Its kind of rough! We were only able to grasp how all the technologies worked near the end of development. And realising that this app is more of a proof of concept than anything does smart a little, as I have no clue how much longevity is in here. (But I am super happy with the experience of osoc & having a great team but don't tell them that shush)

**Comment by Matei9721** [comment]
Finished and added to the dosier
